"use client";

import { ArrowRight, FileText } from "lucide-react";
import { PAPER_PDF } from "@/lib/config";

const changes = [
  ["Dataset", "About 1,200 rows, mostly synthetic, one crop (rice)", "2,200 real samples, 22 crops"],
  ["Task", "Field condition, yield, planting time, next crop", "Crop recommendation plus an explainable field check"],
  ["Labels", "Field condition derived from fixed threshold rules", "The ground-truth crop for each sample"],
  ["Evaluation", "Single split", "5-fold CV plus a stratified hold-out, with the script published"],
  ["Deployment", "Local Flask prototype", "Public API, live demo, open source"],
];

export default function PaperSection() {
  return (
    <section id="paper" className="section-shell fade-bottom bg-[#08100d]">
      <div className="section-inner">
        <p className="section-label">The paper</p>
        <div className="mt-4 grid items-start gap-8 lg:grid-cols-[1.3fr_0.7fr]">
          <div>
            <h2 className="section-title">EnviroSense: AI-Driven Microclimate Control for Sustainable Agriculture Using Edge Computing</h2>
            <p className="mt-4 font-mono text-sm text-textMuted">Muhammad Hamza Faisal &amp; Haydar Cukurtepe · Valparaiso University · 2024</p>
            <p className="mt-6 text-lg leading-8 text-textMuted">
              The paper proposes a low-cost system that combines IoT sensors, machine learning and a mobile app to give small and
              medium-scale farms the kind of microclimate insight usually reserved for large agribusiness. It covers the system
              architecture, a React Native app with role-based access, and a comparison of Random Forest against linear baselines
              for agricultural prediction tasks.
            </p>
            <div className="mt-8 flex flex-wrap gap-4">
              <a href={PAPER_PDF} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 rounded-lg bg-accent px-6 py-3 font-semibold text-bg">
                <FileText size={18} /> Read the paper (PDF)
              </a>
              <a href="#demo" className="flex items-center gap-2 rounded-lg border border-accent px-6 py-3 font-semibold text-accent">
                Try the live system <ArrowRight size={18} />
              </a>
            </div>
          </div>
          <div className="card p-6">
            <p className="font-semibold">Keywords</p>
            <div className="mt-3 flex flex-wrap gap-2">
              {["Microclimate control", "Mobile edge computing", "IoT", "Random Forest", "Sustainable farming", "Crop yield"].map(k => (
                <span key={k} className="rounded-full border border-border px-3 py-1 text-xs text-textMuted">{k}</span>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-14">
          <h3 className="text-2xl font-bold">From paper to production</h3>
          <p className="mt-3 max-w-3xl leading-7 text-textMuted">
            When we rebuilt the prototype for public use, we re-audited the original models. Most of the paper&apos;s training data and several
            of its labels were synthetic, and the field-condition label was generated by the same rules the model was learning, so
            those accuracy figures don&apos;t measure real-world skill. The live system replaces them with a real dataset and an
            evaluation anyone can reproduce.
          </p>
          <div className="mt-6 overflow-x-auto">
            <table className="w-full min-w-[640px] text-left text-sm">
              <thead>
                <tr className="border-b border-border text-textMuted">
                  <th className="py-3 pr-4 font-normal"></th>
                  <th className="py-3 pr-4 font-normal">Paper (2024)</th>
                  <th className="py-3 font-normal text-accent">Live system (v2)</th>
                </tr>
              </thead>
              <tbody>
                {changes.map(([k, a, b]) => (
                  <tr key={k} className="border-b border-border/60">
                    <td className="py-3 pr-4 font-semibold">{k}</td>
                    <td className="py-3 pr-4 text-textMuted">{a}</td>
                    <td className="py-3 text-textPrimary">{b}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  );
}
